import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body>
        {children}
        <Script src="https://cdn.portone.io/v2/browser-sdk.js" strategy="afterInteractive" />
      </body>
    </html>
  );
}

async function waitForPortOne() {
  const begin = Date.now();
  while (!window.PortOne?.requestPayment) {
    if (Date.now() - begin > 5000) throw new Error("PortOne SDK load timeout");
    await new Promise(r => setTimeout(r, 50));
  }
  return window.PortOne;
}